// Scatters the bog's residents across the whole page at runtime.
//
// A repeating tile always shows its seam eventually — you start recognising the
// same heron. So instead the motifs (public/bog-motifs.svg, generated by
// scripts/bog-pattern/gen.py) are placed once across the full document with
// blue-noise spacing: every point is the farthest of several candidates from
// everything already placed, which spreads them evenly without a grid.
//
// Without JS the page keeps its wash and grain, just no creatures.

const SPRITE = "/bog-motifs.svg";
const DENSITY = 1 / 95_000; // motifs per px² of page area
const CANDIDATES = 18; // tries per point — higher is more even, slower
const MIN_GAP = 130; // px; below this a point is rejected outright
const CAP = 900; // safety limit on very long pages

// Rarity: an eagle overhead should feel like an event, laurel is everywhere.
const WEIGHTS: Record<string, number> = {
  laurel: 3,
  blueberry: 3,
  finch: 3,
  sundew: 2,
  pitcher: 2,
  chipmunk: 2,
  squirrel: 2,
  heron: 2,
  beaver: 1,
  eagle: 1,
};

const FLIERS = new Set(["heron", "eagle", "finch"]);

type Motif = { id: string; aspect: number; height: number };

function pickWeighted(motifs: Motif[], weights: number[], r: number) {
  const total = weights.reduce((a, b) => a + b, 0);
  let t = r * total;
  for (let i = 0; i < motifs.length; i++) {
    t -= weights[i];
    if (t <= 0) return i;
  }
  return motifs.length - 1;
}

/** Blue-noise-ish points over w x h, using a grid to keep neighbour checks cheap. */
function scatter(w: number, h: number, count: number): Array<[number, number]> {
  const cell = MIN_GAP;
  const cols = Math.max(1, Math.ceil(w / cell));
  const rows = Math.max(1, Math.ceil(h / cell));
  const grid: Array<Array<[number, number]>> = Array.from({ length: cols * rows }, () => []);
  const near = (x: number, y: number) => {
    const cx = Math.min(cols - 1, Math.floor(x / cell));
    const cy = Math.min(rows - 1, Math.floor(y / cell));
    let best = Infinity;
    for (let gx = cx - 1; gx <= cx + 1; gx++) {
      for (let gy = cy - 1; gy <= cy + 1; gy++) {
        if (gx < 0 || gy < 0 || gx >= cols || gy >= rows) continue;
        for (const [px, py] of grid[gy * cols + gx]) {
          const d = Math.hypot(x - px, y - py);
          if (d < best) best = d;
        }
      }
    }
    return best;
  };

  const points: Array<[number, number]> = [];
  for (let i = 0; i < count; i++) {
    let best: [number, number] | null = null;
    let bestDist = -1;
    for (let c = 0; c < CANDIDATES; c++) {
      const x = Math.random() * w;
      const y = Math.random() * h;
      const d = near(x, y);
      if (d > bestDist) {
        best = [x, y];
        bestDist = d;
      }
    }
    if (!best || bestDist < MIN_GAP * 0.55) continue; // too crowded here
    points.push(best);
    const gx = Math.min(cols - 1, Math.floor(best[0] / cell));
    const gy = Math.min(rows - 1, Math.floor(best[1] / cell));
    grid[gy * cols + gx].push(best);
  }
  return points;
}

async function init() {
  if (document.querySelector("[data-bog-scatter]")) return;

  let spriteText: string;
  try {
    spriteText = await (await fetch(SPRITE)).text();
  } catch {
    return; // no creatures is a fine outcome
  }

  // Inline the sprite so <use href="#bog-*"> resolves (external refs don't).
  const holder = document.createElement("div");
  holder.setAttribute("aria-hidden", "true");
  holder.style.display = "none";
  holder.innerHTML = spriteText.replace(/<\?xml[^>]*\?>/, "");
  document.body.appendChild(holder);

  const motifs: Motif[] = Array.from(holder.querySelectorAll("symbol")).map((sym) => {
    const [, , vw, vh] = (sym.getAttribute("viewBox") ?? "0 0 1 1").split(" ").map(Number);
    return {
      id: sym.id,
      aspect: vw / vh,
      height: Number(sym.dataset.height ?? 36),
    };
  });
  if (!motifs.length) return;
  const weights = motifs.map((m) => WEIGHTS[m.id.replace("bog-", "")] ?? 1);

  const layer = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  layer.setAttribute("data-bog-scatter", "");
  layer.setAttribute("aria-hidden", "true");
  document.body.appendChild(layer);

  let lastWidth = 0;
  let filledTo = 0; // how far down the page we've already populated
  let total = 0;

  function paint() {
    const w = document.documentElement.clientWidth;
    const h = Math.max(document.body.scrollHeight, window.innerHeight);

    // Lazy-loading photos keep growing the page. Rescattering the whole thing
    // would visibly reshuffle what's already on screen, so only the newly
    // revealed band gets populated; a width change does start over.
    const widthChanged = w !== lastWidth;
    if (!widthChanged && h - filledTo < 300) return;
    if (widthChanged) {
      layer.replaceChildren();
      filledTo = 0;
      total = 0;
      lastWidth = w;
    }

    layer.setAttribute("viewBox", `0 0 ${w} ${h}`);
    layer.setAttribute("width", String(w));
    layer.setAttribute("height", String(h));

    const bandTop = filledTo;
    const bandHeight = h - bandTop;
    const room = Math.max(0, CAP - total);
    const count = Math.min(room, Math.round(w * bandHeight * DENSITY));
    filledTo = h;
    if (!count) return;
    total += count;

    const svgns = "http://www.w3.org/2000/svg";
    const frag = document.createDocumentFragment();
    for (const [x, yLocal] of scatter(w, bandHeight, count)) {
      const y = yLocal + bandTop;
      const m = motifs[pickWeighted(motifs, weights, Math.random())];
      const scale = 0.8 + Math.random() * 0.4;
      const height = m.height * scale;
      const width = height * m.aspect;
      const use = document.createElementNS(svgns, "use");
      use.setAttribute("href", `#${m.id}`);
      use.setAttribute("width", width.toFixed(1));
      use.setAttribute("height", height.toFixed(1));
      const flip = Math.random() < 0.5 ? -1 : 1;
      const rot = FLIERS.has(m.id.replace("bog-", "")) ? (Math.random() * 18 - 9).toFixed(1) : "0";
      use.setAttribute(
        "transform",
        `translate(${x.toFixed(1)} ${y.toFixed(1)}) rotate(${rot}) scale(${flip} 1)`,
      );
      frag.appendChild(use);
    }
    layer.appendChild(frag);
  }

  paint();

  let resizeTimer: number | undefined;
  const schedule = () => {
    window.clearTimeout(resizeTimer);
    resizeTimer = window.setTimeout(paint, 250);
  };
  window.addEventListener("resize", schedule, { passive: true });
  // Lazy-loaded photos keep growing the page; watch for that and extend.
  new ResizeObserver(schedule).observe(document.body);
}

if (document.readyState === "loading") {
  document.addEventListener("DOMContentLoaded", init);
} else {
  init();
}
