// Single place that turns a photo key (path relative to the repo photos/ dir)
// into a URL. In dev it points at the local sharp resizer
// (scripts/dev-image-server.mjs); in prod it points at WebP renders
// pre-generated by scripts/prerender-images.mjs and shipped inside the Pages
// deploy under /img/<width>/<key>.webp — samuelclay.com's DNS lives off
// Cloudflare, so zone features like /cdn-cgi/image transforms aren't
// available and the ladder is baked at build time instead.
//
// Env (optional): PUBLIC_DEV_IMG — dev resizer origin (default :8788).

import { STRIP_WIDTHS, FULL_WIDTHS } from "./image-widths.mjs";

const DEV = import.meta.env.DEV;
const DEV_IMG = import.meta.env.PUBLIC_DEV_IMG ?? "http://localhost:8788";

export type Fit = "cover" | "contain";

export interface ImageOpts {
  /** Target width in CSS pixels (before DPR). Must be in ALL_WIDTHS (image-widths.mjs). */
  w: number;
  /** Cropping is done client-side with CSS object-fit; only the dev resizer sees this. */
  fit?: Fit;
  /** Quality 1–100. Prod renders are fixed at q78; only the dev resizer honors this. */
  q?: number;
  /**
   * Cache-busting fingerprint of the source photo (e.g. "3024x4032").
   * Replacing a photo under the same key changes its dims, which changes the
   * URL — otherwise browsers/CDNs keep serving the old render for up to their
   * full TTL, and JS-initiated loads (the lightbox) ignore hard reloads.
   */
  v?: string;
}

const enc = (key: string) => key.split("/").map(encodeURIComponent).join("/");

export function imageUrl(key: string, { w, fit = "cover", q = 78, v }: ImageOpts): string {
  if (DEV) {
    const ver = v ? `&v=${encodeURIComponent(v)}` : "";
    return `${DEV_IMG}/img/${enc(key)}?w=${w}&fit=${fit}&q=${q}${ver}`;
  }
  return `/img/${w}/${enc(key)}.webp${v ? `?v=${encodeURIComponent(v)}` : ""}`;
}

/**
 * URL for a video key (path relative to photos/). Unlike images there is no
 * ladder — the clip is transcoded once by the ingest step and served as-is:
 * from the dev server's /video route in dev, and from dist/video/<key> in
 * prod (copied there by scripts/prerender-images.mjs).
 */
export function videoUrl(key: string): string {
  return DEV ? `${DEV_IMG}/video/${enc(key)}` : `/video/${enc(key)}`;
}

/** Build a srcset across widths for responsive <img>. */
export function srcset(key: string, widths: number[], fit: Fit = "cover", q = 78, v?: string): string {
  return widths.map((w) => `${imageUrl(key, { w, fit, q, v })} ${w}w`).join(", ");
}

// Width ladders used around the site (defined in image-widths.mjs so the
// prerender script can read the same list).
export { STRIP_WIDTHS, FULL_WIDTHS };
